version: "3.8"

services:
  # Development DB service
  dev-db:
    image: mariadb:latest
    container_name: dev-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: dev_db_product_managements
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_password
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Spring Boot application
  app:
    build:
      context: .
    container_name: catalogue-app
    environment:
      SPRING_PROFILES_ACTIVE: dev # Set active profile to dev
    ports:
      - "9090:8082" # Maps app port
    depends_on:
      - dev-db
    networks:
      - app-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: dev-db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8080:80" # Exposes phpMyAdmin for dev only
    depends_on:
      - dev-db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
