version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestion-produits-app
    ports:
      - '8080:8080'
    depends_on:
      - oracle
    networks:
      - spring-network

  oracle:
    image: 'gvenzl/oracle-free:latest'
    container_name: oracle-db
    environment:
      - ORACLE_PASSWORD=secret
    ports:
      - '1521:1521'
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge
