spring:
  datasource:
    url: jdbc:mariadb://dev-db:3306/dev_db_product_managements # Matches dev-db service in compose.yaml
    username: dev_user
    password: dev_password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # Update database schema; avoid 'create-drop' for persistence
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
  security:
    jdbc:
      authentication:
        enabled: false # Disable built-in Spring Security JDBC authentication for now

logging:
  level:
    org.springframework.security: DEBUG # Debug logs for security configuration
